---
- name: update main supervisor
  command: supervisorctl -c /etc/supervisor/supervisord.conf update

- name: restart remote_syslog
  command: supervisorctl -c /etc/supervisor/supervisord.conf restart all